import { projectClient } from '../services/project-client.js';

const OBJECT_TYPES = ['Base Cabinet', 'Wall Cabinet', 'Tall Cabinet', 'Wardrobe', 'TV Cabinet', 'Shoe Cabinet', 'Vanity Cabinet', 'Display Cabinet', 'Pantry Cabinet', 'Custom Cabinet'];
const STATUSES = ['Recognized', 'Engineering Matched', 'Object Generated', 'Validation Required', 'Production Ready', 'User Confirmation Required'];
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const optionList = (values, selected) => values.map((value) => `<option value="${esc(value)}" ${value === selected ? 'selected' : ''}>${esc(value)}</option>`).join('');
const collectNodes = (project, type) => { const result = []; const visit = (node) => { if (node?.type === type) result.push(node); (node?.children || []).forEach(visit); }; (project?.hierarchy?.floors || []).forEach(visit); return result; };
const treeRows = (nodes, depth = 0) => nodes.map((node) => `<button class="furniture-tree-row" type="button" data-select="${esc(node.objectId)}" style="--tree-depth:${depth}"><span>${node.children?.length ? '▾' : '·'}</span><strong>${esc(node.name)}</strong><small>${esc(node.objectType)}</small></button>${treeRows(node.children || [], depth + 1)}`).join('');

export async function FurnitureObjectEditor({ projectId, router }) {
  const [project, listed, hierarchy, catalog, hardwareCatalog] = await Promise.all([projectClient.getProject(projectId), projectClient.listFurnitureObjects(projectId), projectClient.getFurnitureObjectHierarchy(projectId), projectClient.listOfficialMaterials(), projectClient.listOfficialHardware()]);
  let objects = listed.furnitureObjects || [];
  let tree = hierarchy.hierarchy || [];
  let selectedObjectId = objects[0]?.objectId || null;
  let validationResult = null;
  const materials = catalog.materials || [];
  const hardware = hardwareCatalog.hardware || [];
  const confirmedRecords = (project.engineeringRecords || []).filter((record) => record.status === 'Confirmed');
  const floors = collectNodes(project, 'Floor');
  const rooms = collectNodes(project, 'Room');
  const section = document.createElement('section'); section.className = 'furniture-editor-page';
  const refresh = async (message = '') => { const [next, nextTree] = await Promise.all([projectClient.listFurnitureObjects(projectId), projectClient.getFurnitureObjectHierarchy(projectId)]); objects = next.furnitureObjects || []; tree = nextTree.hierarchy || []; if (!objects.some((item) => item.objectId === selectedObjectId)) selectedObjectId = objects[0]?.objectId || null; render(message); };
  const render = (message = '') => {
    const selected = objects.find((object) => object.objectId === selectedObjectId) || null;
    const dimensions = selected?.dimensions || { width: null, height: null, depth: null, thickness: null, unit: null };
    const assigned = selected?.materialReferences || [];
    const assignedIds = new Set(assigned.map((reference) => reference.materialId));
    const assignedHardware = selected?.hardwareReferences || [];
    const assignedHardwareIds = new Set(assignedHardware.map((reference) => reference.hardwareId));
    const cadDocuments = (project.projectDocuments?.documents || []).filter((document) => ['DWG', 'DXF'].includes(String(document.sourceFormat || document.documentType || '').toUpperCase()));
    const materialRows = assigned.length ? assigned.map((reference) => { const material = materials.find((item) => item.id === reference.materialId); return `<div class="furniture-material-row"><div><strong>${esc(material?.officialName || 'Unknown Material')}</strong><small>${esc(reference.materialId)} · ${esc(material?.specification || 'Catalog data unavailable')} · ${esc(material?.thickness || 'Thickness unavailable')}</small></div><button class="button danger" type="button" data-remove-material="${esc(reference.materialId)}">Remove</button></div>`; }).join('') : '<div class="furniture-editor-empty">No materials assigned.</div>';
    const materialCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Material Assignment</p><h2>Assigned Materials</h2></div></div><div class="furniture-material-list">${materialRows}</div><form data-material-form class="furniture-material-form"><label>Official Material<select name="materialId"><option value="">Select material</option>${materials.filter((material) => !assignedIds.has(material.id)).map((material) => `<option value="${esc(material.id)}">${esc(material.id)} — ${esc(material.officialName)}</option>`).join('')}</select></label><button class="button primary" type="submit">Assign Material</button></form></section>` : '';
    const hardwareRows = assignedHardware.length ? assignedHardware.map((reference) => { const item = hardware.find((record) => record.id === reference.hardwareId); return `<div class="furniture-material-row"><div><strong>${esc(item?.officialName || 'Unknown Hardware')}</strong><small>${esc(reference.hardwareId)} · ${esc(item?.category || 'Catalog data unavailable')} · ${esc(item?.unit || 'Unit unavailable')}</small></div><button class="button danger" type="button" data-remove-hardware="${esc(reference.hardwareId)}">Remove</button></div>`; }).join('') : '<div class="furniture-editor-empty">No hardware assigned.</div>';
    const hardwareCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Hardware Assignment</p><h2>Assigned Hardware</h2></div></div><div class="furniture-material-list">${hardwareRows}</div><form data-hardware-form class="furniture-material-form"><label>Official Hardware<select name="hardwareId"><option value="">Select hardware</option>${hardware.filter((item) => !assignedHardwareIds.has(item.id)).map((item) => `<option value="${esc(item.id)}">${esc(item.id)} — ${esc(item.officialName)}</option>`).join('')}</select></label><button class="button primary" type="submit">Assign Hardware</button></form></section>` : '';
    const dimensionCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Engineering Dimensions</p><h2>Dimensions</h2></div></div><form data-dimensions-form class="furniture-editor-form furniture-dimensions-form"><label>Width<input name="width" type="number" min="0" step="any" value="${dimensions.width ?? ''}"></label><label>Height<input name="height" type="number" min="0" step="any" value="${dimensions.height ?? ''}"></label><label>Depth<input name="depth" type="number" min="0" step="any" value="${dimensions.depth ?? ''}"></label><label>Thickness<input name="thickness" type="number" min="0" step="any" value="${dimensions.thickness ?? ''}"></label><label>Unit<input value="${esc(dimensions.unit || 'Not defined by PRD') }" readonly></label><button class="button primary" type="submit">Save Dimensions</button></form></section>` : '';
    const validationCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Object Validation</p><h2>${validationResult?.isValid ? 'Valid' : validationResult ? 'Issues Found' : 'Not Checked'}</h2></div><button class="button" type="button" data-validate>Validate Object</button></div>${validationResult ? (validationResult.errors.length ? `<ul class="furniture-validation-errors">${validationResult.errors.map((error) => `<li><strong>${esc(error.code)}</strong><span>${esc(error.message)}</span></li>`).join('')}</ul>` : '<p class="furniture-validation-valid">No validation errors.</p>') : '<p class="muted">Validation is read-only and does not modify the object.</p>'}</section>` : '';
    const cadRows = selected?.cadReferences?.length ? selected.cadReferences.map((reference) => `<div class="furniture-material-row"><div><strong>${esc(cadDocuments.find((document) => (document.id || document.drawingId) === reference.drawingId)?.originalFileName || reference.drawingId)}</strong><small>Drawing: ${esc(reference.drawingId)} · Entities: ${esc((reference.entityIds || []).join(', ') || 'all not specified')}</small></div><button class="button danger" type="button" data-remove-cad="${esc(reference.drawingId)}">Remove</button></div>`).join('') : '<div class="furniture-editor-empty">No CAD references assigned.</div>';
    const cadCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">CAD Synchronization</p><h2>CAD References</h2></div></div><div class="furniture-material-list">${cadRows}</div>${cadDocuments.length ? `<form data-cad-form class="furniture-material-form"><label>CAD Drawing<select name="drawingId"><option value="">Select drawing</option>${cadDocuments.map((document) => `<option value="${esc(document.id || document.drawingId)}">${esc(document.originalFileName || document.fileName || document.id)} · ${esc(String(document.sourceFormat || document.documentType || '').toUpperCase())}</option>`).join('')}</select></label><label>Entity IDs <small>(comma separated; IDs are read from the selected drawing)</small><input name="entityIds" placeholder="entity-0, entity-1"></label><button class="button primary" type="submit">Sync CAD Reference</button></form>` : '<p class="muted">No DWG or DXF drawing exists in this Project.</p>'}</section>` : '';
    const formulaRows = selected?.formulaReferences?.length ? selected.formulaReferences.map((reference) => `<div class="furniture-material-row"><div><strong>${esc(reference.formulaId)}</strong><small>Official Formula Catalog reference</small></div><button class="button danger" type="button" data-remove-formula="${esc(reference.formulaId)}">Remove</button></div>`).join('') : '<div class="furniture-editor-empty">No Formula References assigned.</div>';
    const formulaCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Formula Synchronization</p><h2>Formula References</h2></div></div><div class="furniture-material-list">${formulaRows}</div><p class="muted">Formula definitions and calculations remain owned by the Official Engineering Knowledge Base. No formula catalog is configured in this build.</p></section>` : '';
    const createCard = `<section class="furniture-editor-card" data-create-panel hidden><h2>Create Furniture Object</h2>${confirmedRecords.length && floors.length && rooms.length ? `<form data-create-form class="furniture-editor-form"><label>Name<input name="name" required maxlength="120"></label><label>Object Type<select name="objectType">${optionList(OBJECT_TYPES, OBJECT_TYPES[0])}</select></label><label>Engineering Record<select name="engineeringRecordId">${confirmedRecords.map((record) => `<option value="${esc(record.id)}">${esc(record.id)}</option>`).join('')}</select></label><label>Floor<select name="floorId">${floors.map((item) => `<option value="${esc(item.id)}">${esc(item.name || item.id)}</option>`).join('')}</select></label><label>Room<select name="roomId">${rooms.map((item) => `<option value="${esc(item.id)}">${esc(item.name || item.id)}</option>`).join('')}</select></label><button class="button primary" type="submit">Create</button></form>` : '<div class="furniture-editor-empty">A confirmed Engineering Record, Floor and Room are required before creation.</div>'}</section>`;
    const objectCard = selected ? `<section class="furniture-editor-card"><div class="furniture-editor-card__heading"><div><p class="eyebrow">Selected Object</p><h2>${esc(selected.name)}</h2></div><button class="button danger" type="button" data-delete>Archive Object</button></div><form data-edit-form class="furniture-editor-form"><label>Name<input name="name" value="${esc(selected.name)}" required maxlength="120"></label><label>Object Type<select name="objectType">${optionList(OBJECT_TYPES, selected.objectType)}</select></label><label>Production Status<select name="status">${optionList(STATUSES, selected.productionStatus)}</select></label><button class="button primary" type="submit">Save Object</button></form><dl class="furniture-object-properties"><div><dt>Object ID</dt><dd><code>${esc(selected.objectId)}</code></dd></div><div><dt>Project ID</dt><dd><code>${esc(selected.projectId)}</code></dd></div><div><dt>Engineering Record</dt><dd><code>${esc(selected.engineeringRecordId)}</code></dd></div><div><dt>Created</dt><dd>${esc(selected.createdAt)}</dd></div><div><dt>Updated</dt><dd>${esc(selected.updatedAt)}</dd></div></dl></section>` : '<section class="furniture-editor-card furniture-editor-empty">Select a Furniture Object to inspect its properties.</section>';
    section.innerHTML = `<header class="furniture-editor-header"><div><p class="eyebrow">Furniture Object Engine</p><h1>Furniture Object Editor</h1><p class="muted">Project: ${esc(project.project?.name || projectId)}</p></div><div class="furniture-editor-header__actions"><button class="button" type="button" data-back>Back to Project</button><button class="button primary" type="button" data-toggle-create>Create Furniture Object</button></div></header><p class="furniture-editor-message">${esc(message)}</p><div class="furniture-editor-layout"><aside class="furniture-editor-sidebar"><div class="furniture-editor-panel-heading"><strong>Furniture Objects</strong><span>${objects.length}</span></div><div class="furniture-object-list">${objects.length ? objects.map((object) => `<button class="furniture-object-row" type="button" data-select="${esc(object.objectId)}"><strong>${esc(object.name)}</strong><small>${esc(object.objectType)} · ${esc(object.productionStatus || 'No status')}</small><code>${esc(object.objectId)}</code></button>`).join('') : '<div class="furniture-editor-empty">No Furniture Objects in this Project.</div>'}</div><div class="furniture-editor-panel-heading"><strong>Hierarchy</strong><span>Engine</span></div><div class="furniture-tree">${tree.length ? treeRows(tree) : '<div class="furniture-editor-empty">No hierarchy data.</div>'}</div></aside><main class="furniture-editor-main">${createCard}${objectCard}${dimensionCard}${validationCard}${cadCard}${formulaCard}${materialCard}${hardwareCard}</main></div>`;
    section.querySelector('[data-back]').onclick = () => router.navigate(`/dashboard/${encodeURIComponent(projectId)}`); section.querySelector('[data-toggle-create]').onclick = () => { const panel = section.querySelector('[data-create-panel]'); panel.hidden = !panel.hidden; }; section.querySelectorAll('[data-select]').forEach((button) => { button.onclick = () => { selectedObjectId = button.dataset.select; render(); }; });
    section.querySelector('[data-create-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const record = confirmedRecords.find((item) => item.id === form.get('engineeringRecordId')); try { await projectClient.createFurnitureObject(projectId, { name: form.get('name'), objectType: form.get('objectType'), floorId: form.get('floorId'), roomId: form.get('roomId'), confirmedEngineeringRecord: record }); await refresh('Furniture Object created.'); } catch (error) { render(error.message); } });
    section.querySelector('[data-edit-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await projectClient.updateFurnitureObject(projectId, selectedObjectId, { name: form.get('name'), objectType: form.get('objectType'), status: form.get('status') }); await refresh('Furniture Object saved.'); } catch (error) { render(error.message); } });
    section.querySelector('[data-delete]')?.addEventListener('click', async () => { try { await projectClient.deleteFurnitureObject(projectId, selectedObjectId); selectedObjectId = null; await refresh('Furniture Object archived.'); } catch (error) { render(error.message); } });
    section.querySelector('[data-material-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const materialId = new FormData(event.currentTarget).get('materialId'); if (!materialId) return; try { await projectClient.assignFurnitureObjectMaterial(projectId, selectedObjectId, materialId); await refresh('Material assigned.'); } catch (error) { render(error.message); } });
    section.querySelectorAll('[data-remove-material]').forEach((button) => button.addEventListener('click', async () => { try { await projectClient.removeFurnitureObjectMaterial(projectId, selectedObjectId, button.dataset.removeMaterial); await refresh('Material removed.'); } catch (error) { render(error.message); } }));
    section.querySelector('[data-hardware-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const hardwareId = new FormData(event.currentTarget).get('hardwareId'); if (!hardwareId) return; try { await projectClient.assignFurnitureObjectHardware(projectId, selectedObjectId, hardwareId); await refresh('Hardware assigned.'); } catch (error) { render(error.message); } });
    section.querySelectorAll('[data-remove-hardware]').forEach((button) => button.addEventListener('click', async () => { try { await projectClient.removeFurnitureObjectHardware(projectId, selectedObjectId, button.dataset.removeHardware); await refresh('Hardware removed.'); } catch (error) { render(error.message); } }));
    section.querySelector('[data-dimensions-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const changes = {}; ['width', 'height', 'depth', 'thickness'].forEach((field) => { const value = form.get(field); if (value !== '') changes[field] = Number(value); }); try { await projectClient.updateFurnitureObjectDimensions(projectId, selectedObjectId, changes); await refresh('Dimensions saved.'); } catch (error) { render(error.message); } });
    section.querySelector('[data-validate]')?.addEventListener('click', async () => { try { const result = await projectClient.validateFurnitureObject(projectId, selectedObjectId); validationResult = result.validation; render(); } catch (error) { render(error.message); } });
    section.querySelector('[data-cad-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const drawingId = form.get('drawingId'); if (!drawingId) return; const entityIds = String(form.get('entityIds') || '').split(',').map((value) => value.trim()).filter(Boolean); try { await projectClient.syncFurnitureObjectCadReference(projectId, selectedObjectId, { drawingId, entityIds }); await refresh('CAD reference synchronized.'); } catch (error) { render(error.message); } });
    section.querySelectorAll('[data-remove-cad]').forEach((button) => button.addEventListener('click', async () => { try { await projectClient.removeFurnitureObjectCadReference(projectId, selectedObjectId, button.dataset.removeCad); await refresh('CAD reference removed.'); } catch (error) { render(error.message); } }));
    section.querySelectorAll('[data-remove-formula]').forEach((button) => button.addEventListener('click', async () => { try { await projectClient.removeFurnitureObjectFormula(projectId, selectedObjectId, button.dataset.removeFormula); await refresh('Formula reference removed.'); } catch (error) { render(error.message); } }));
  };
  render(); return section;
}
