import { projectClient } from '../services/project-client.js';

export function ProjectList({ router, onOpen }) {
  const section = document.createElement('section'); section.className = 'page project-list-page';
  section.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Project System</p><h2>Projects</h2><p class="muted">Your offline project workspace.</p></div><button class="button primary" data-create>+ New project</button></div><div class="toolbar"><input aria-label="Search projects" placeholder="Search projects" data-search /><button class="button" data-archive>Archive</button><button class="button" data-trash>Trash</button><button class="button" data-database>Database</button><button class="button" data-settings>Settings</button></div><div class="project-grid" data-list><div class="empty-state">Loading projects…</div></div>`;
  const list = section.querySelector('[data-list]'); let projects = []; let filter = new URLSearchParams(window.location.hash.split('?')[1] || '').get('filter') || 'active';
  const draw = () => { const query = section.querySelector('[data-search]').value.toLowerCase(); const filtered = projects.filter((p) => (filter === 'all' || p.project.archiveStatus.toLowerCase() === filter) && p.project.name.toLowerCase().includes(query)); list.innerHTML = filtered.length ? filtered.map((p) => `<article class="project-card"><div class="project-card-top"><span class="status-pill">${p.project.archiveStatus}</span><span class="muted">${new Date(p.project.updatedAt).toLocaleDateString()}</span></div><h3>${p.project.name}</h3><p class="muted">${p.project.status} · ${p.project.workflowStatus}</p><button class="button" data-open="${p.project.id}" ${p.project.archiveStatus === 'Trash' ? 'disabled' : ''}>Open project</button><div class="card-actions">${p.project.archiveStatus === 'Active' ? `<button class="button" data-action="archive" data-id="${p.project.id}">Archive</button><button class="button" data-action="trash" data-id="${p.project.id}">Trash</button>` : `<button class="button" data-action="restore" data-id="${p.project.id}">Restore</button>`}</div></article>`).join('') : '<div class="empty-state">No projects found.</div>'; list.querySelectorAll('[data-open]').forEach((button) => button.addEventListener('click', () => onOpen(button.dataset.open))); list.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', async () => { try { await projectClient[`${button.dataset.action}Project`](button.dataset.id); projects = await projectClient.listProjects(); draw(); } catch (error) { list.innerHTML = `<div class="empty-state">${error.message}</div>`; } })); };
  projectClient.listProjects().then((data) => { projects = data; draw(); }).catch((error) => { list.innerHTML = `<div class="empty-state">${error.message}</div>`; });
  section.querySelector('[data-search]').addEventListener('input', draw);
  section.querySelector('[data-create]').addEventListener('click', async () => { const name = window.prompt('Project name', 'New Project'); if (!name?.trim()) return; try { const created = await projectClient.createProject(name.trim()); projects = [created, ...projects]; draw(); onOpen(created.project.id); } catch (error) { list.innerHTML = `<div class="empty-state">${error.message}</div>`; } });
  section.querySelector('[data-archive]').addEventListener('click', () => { filter = 'archived'; draw(); });
  section.querySelector('[data-trash]').addEventListener('click', () => { filter = 'trash'; draw(); });
  section.querySelector('[data-database]').addEventListener('click', () => router.navigate('/database'));
  section.querySelector('[data-settings]').addEventListener('click', () => router.navigate('/settings'));
  return section;
}
