import { projectClient } from '../services/project-client.js';

export async function ProjectDashboard({ projectId, router }) {
  let project = await projectClient.getProject(projectId); const section = document.createElement('section'); section.className = 'page dashboard-page';
  const cards = ['Original PDF', 'Editable PDF', 'Production Review', 'Purchase List', 'Cutting Summary', 'Cabinet Production', 'Production Requirements', 'Project Documents'];
  const render = () => { section.innerHTML = `<div class="page-heading"><div><button class="back-link" data-back>← Projects</button><p class="eyebrow">Project Dashboard</p><h2>${project.project.name}</h2><p class="muted">${project.project.status} · ${project.project.workflowStatus} · ${project.project.archiveStatus}</p></div><button class="button" data-settings>Project Settings</button></div><div class="state-strip"><span>Status<strong>${project.project.status}</strong></span><span>Workflow<strong>${project.project.workflowStatus}</strong></span><span>Lock<strong>${project.project.lockStatus}</strong></span><span>Revision<strong>${project.project.activeRevisionId ? 'Confirmed' : 'Working only'}</strong></span><span>Snapshot<strong>${project.project.activeSnapshotId ? 'Available' : 'Not created'}</strong></span></div><div class="dashboard-grid">${cards.map((title) => `<button class="dashboard-card" type="button" data-placeholder="${title}"><span>${title}</span><small>Boundary ready · feature scope follows later Sprint</small></button>`).join('')}</div><div class="dashboard-columns"><div class="panel"><h3>Working State</h3><textarea data-working-state rows="3" placeholder="Add a working note">${project.workingState.note || ''}</textarea><button class="button primary" data-save>Save working state</button><p class="muted" data-save-status>Changes remain in Working State until a later confirmation flow.</p></div><div class="panel"><h3>Rooms & cabinets</h3><div class="tree-list">${project.hierarchy.floors.map((floor) => `<div><strong>${floor.name}</strong>${(floor.children || []).map((room) => `<div class="tree-child">${room.name}${(room.children || []).filter((item) => item.type === 'Furniture').map((item) => `<span class="tree-tag">${item.name}</span>`).join('')}</div>`).join('')}</div>`).join('') || '<p class="muted">No floors added yet.</p>'}</div></div></div><div class="panel activity-panel"><h3>Project History / Recent Activity</h3><div class="activity-list">${project.history.slice().reverse().map((item) => `<div><strong>${item.type}</strong><span class="muted">${new Date(item.createdAt).toLocaleString()}</span></div>`).join('')}</div></div>`; bind(); };
  const bind = () => { section.querySelector('[data-back]').addEventListener('click', () => router.navigate('/projects')); section.querySelector('[data-settings]').addEventListener('click', () => router.navigate(`/settings?project=${projectId}`)); section.querySelector('[data-save]').addEventListener('click', async () => { const status = section.querySelector('[data-save-status]'); try { project = await projectClient.saveWorkingState(projectId, { note: section.querySelector('[data-working-state]').value, productionSettings: project.workingState.productionSettings || {} }); render(); } catch (error) { status.textContent = error.message; } }); section.querySelectorAll('[data-placeholder]').forEach((button) => button.addEventListener('click', () => window.alert(`${button.dataset.placeholder} is a reserved boundary; no later-Sprint business logic is enabled.`))); };
  render(); return section;
}
